### ISSUE TITLE
Consider deprecating in favour of http-terminator

### ISSUE THREAD

**Issue by gajus** [sebhildebrandt/http-graceful-shutdown#11]
I have answered a variation of "how to terminate a HTTP server" many times on different Node.js support channels. Unfortunately, I couldn't recommend any of the existing libraries because they are lacking in one or another way (https://github.com/gajus/http-terminator#alternative-libraries). I have since put together a package that (I believe) is handling all the cases expected of graceful HTTP termination.

https://github.com/gajus/http-terminator

I would appreciate if you consider contributing to http-terminator and deprecating http-graceful-shutdown.

**Comment by sebhildebrandt** [comment]
I currently work on version 3.0 ... so I will not consider to deprecate this library at the moment.

**Comment by gajus** [comment]
Why not contribute to `http-terminator`?
