### ISSUE TITLE
Forced Exit Shutdown timeout doesn't start until all connections are closed

### ISSUE THREAD

**Issue by S15** [sebhildebrandt/http-graceful-shutdown#15]
### Issue Type: Bug

Long lived keep-alive connections keep server running longer than the `timeout` option with `forceExit` set to `true`.

### Expected behavior

- Connections are forcefully closed after `timeout`.

### Actual behavior

- Server waits until all connections clear before shutting down

### Steps to reproduce the problem

- set forceExit to true
- set timeout to 10 seconds
- make a request that takes some arbitrary amount of time > 10 seconds (my test was set to 80 seconds)
- make a request to the server
- shutdown the server while the request is pending and has more than 10 seconds remaining.
- wait > 10 seconds. The server will not completely shutdown until the request completes

### Specifications
package version: Tested 3.1.1 - issue present.
package version: Tested 3.0.2 - issue **not** present.

### Problem and possible solution

This happens with version 3.1.1. Version 3.0.2 behaves how I expect it to, so it seems like this was introduced with [this commit](https://github.com/sebhildebrandt/http-graceful-shutdown/commit/31ffeca49416e243824698559e748d57f32d7602#diff-92bbac9a308cd5fcf9db165841f2d90ce981baddcb2b1e26cfff170929af3bd1R254). 

As far as I can tell, what is happening is the nested Promise from `cleanupHttp` has to resolve before the next `.then` is executed. This means that we don't start waitForReadyToShutdown until all connections are already closed. I confirmed this locally by changing 
```js
.then(() =>  {
   isShuttingDown = true;
   return cleanupHttp(); // return nested Promise
}.then( /* ... et cetera ...  */)
```
to
```js
.then(() =>  {
   isShuttingDown = true;
   cleanupHttp(); //  fire Promise off and forget about it.
}.then( /* ... et cetera ...  */)
```

**Comment by sebhildebrandt** [comment]
@S15  Fixed it ... thank you. Version 3.1.2 just released
