### ISSUE TITLE
Refactor The Code 

### ISSUE THREAD

**Issue by iamgabrielsoft** [sebhildebrandt/http-graceful-shutdown#18]
### Issue Type

Describe your bug here ...

Can I refactor all the Code to have a base class?

### Expected behavior

-
-
-

### Actual behavior

-
-
-

### Steps to reproduce the problem

-
-
-

### Specifications

- package version:
- operating system:
- hardware:

### Problem and possible solution

If you have a solution in mind (or any idea what could cause this issue), we would be happy, if you can describe it here ...

**Comment by sebhildebrandt** [comment]
@iamgabrielsoft ... I decided to refactor the whole code using TypeScript. This will be my side project for the upcoming two weeks. If you can describe what your intension was, to refactor the code, I can take this into consideration.

**Comment by sebhildebrandt** [comment]
@iamgabrielsoft ... new version will be released end of this month ...
