### ISSUE TITLE
Manual shutdown does not exit the process when there is open connection

### ISSUE THREAD

**Issue by tomasvalentaopenbean** [sebhildebrandt/http-graceful-shutdown#22]
### Issue Type

When using the manual shutdown method to terminate the process (in case some unexpected error happened for example) and there are still some open connection, it does not terminates the process entirely, but it keeps hanging instead.
### Expected behavior

When I call `gracefulShutdown()` method I expect the process to be terminated even if there is some open connections.
### Actual behavior

When I have an open connection to the server and I call `gracefulShutdown()` method, it attempts to close the connections, it "waits to be ready to shutdown", then it attempts to force-close the connections, then it performs "onShutdown" and "finally", but then it keeps hanging and does not terminate the process.

Log output:
```
➜  DEBUG=http-graceful-shutdown node server.js
Listening on port 3000
  http-graceful-shutdown shutdown signal - manual +0ms
  http-graceful-shutdown shutting down +0ms
  http-graceful-shutdown Destroy Connections : close +1ms
  http-graceful-shutdown Connections destroyed : 0 +0ms
  http-graceful-shutdown Connection Counter    : 2 +0ms
  http-graceful-shutdown Secure Connections destroyed : 0 +1ms
  http-graceful-shutdown Secure Connection Counter    : 0 +0ms
  http-graceful-shutdown Close http server +0ms
  http-graceful-shutdown waitForReadyToShutDown... 120 +0ms
  http-graceful-shutdown Schedule the next waitForReadyToShutdown +0ms
  http-graceful-shutdown waitForReadyToShutDown... 119 +251ms
  http-graceful-shutdown Schedule the next waitForReadyToShutdown +1ms
  ...
  http-graceful-shutdown waitForReadyToShutDown... 1 +252ms
  http-graceful-shutdown Schedule the next waitForReadyToShutdown +0ms
  http-graceful-shutdown waitForReadyToShutDown... 0 +250ms
  http-graceful-shutdown Could not close connections in time (30000ms), will forcefully shut down +1ms
  http-graceful-shutdown Do onShutdown now +0ms
  http-graceful-shutdown Destroy Connections : forced close +0ms
  http-graceful-shutdown Connections destroyed : 1 +0ms
  http-graceful-shutdown Connection Counter    : 2 +0ms
  http-graceful-shutdown Secure Connections destroyed : 0 +0ms
  http-graceful-shutdown Secure Connection Counter    : 0 +0ms
SIGNAL: manual
  http-graceful-shutdown executing finally() +1ms
Finally
```
The application hangs and does not terminate.

### Steps to reproduce the problem

In a new folder create a new npm project `npm init -y`
Install required packages `npm i express http-graceful-shutdown`
Create a server.js file with following content
```
const express = require('express');
const gracefulShutdown = require('http-graceful-shutdown');
const app = express();
const port = 3000;

app.get('*', async (req, res) => {
  shutdown();
});

let server = app.listen(port, () => {
  console.log(`Listening on port ${port}`)
});
let shutdown = gracefulShutdown(server, {
  onShutdown: function (sig) { console.log("SIGNAL: " + sig); return Promise.resolve(); },
  finally: () => console.log("Finally")
});
```
Start the server `DEBUG=http-graceful-shutdown node server.js`
Issue a GET request to `http://localhost:3000`
### Specifications

- package version: 3.1.13
- operating system: MacOS 12.6.5
- hardware: Macbook Pro 15' 2015

### Problem and possible solution

Did some debugging but was not able to pin-point the issue exactly.

**Comment by sebhildebrandt** [comment]
@tomasvalentaopenbean thank you for reporting, I will test it and try to figure out what is going on here ... I never experienced anything like that. Will come back to you as soon as I have an idea ;-)

**Comment by sebhildebrandt** [comment]
@tomasvalentaopenbean ... tested and viewed your code ... there are several problems In your code: 

- actually you are using this function not properly. `gracefulShutdown()` instantiates (and enables) all what is needed to make a graceful shutdown. When you *then* are shutting down you app with  CRTL-C or programmatically e.g. by sending a SIGINT, this should work:
- your promise never resolved to true 

So this is how it could be rewritten:

```js
const express = require('express');
const gracefulShutdown = require('http-graceful-shutdown');
const app = express();
const port = 3000;

app.get('*', async (req, res) => {
  process.kill(process.pid, "SIGINT");
});

let server = app.listen(port, () => {
  shutdown(); // instantiate / enable the full shutdown mechanism
  console.log(`Listening on port ${port}`)
});
const shutdown = () => {
    gracefulShutdown(server, {
        onShutdown: function (sig) { console.log("SIGNAL: " + sig); return Promise.resolve(true); },
        finally: () => console.log("Finally")
    });
}
```
Hope this helps! Closing it for now.
