### ISSUE TITLE
typo on Debug section

### ISSUE THREAD

**Issue by sekulicb** [sebhildebrandt/http-graceful-shutdown#6]
Hi guys. You have a typo on Home page under the section 'Debug' where we need to set DEBUG env variable. It should be **http-graceful-shutdown** . I was confused on why debug was not working, then I looked in library to see which namespace is passed to debug npm. Just little observation.

Thanks.

**Comment by sebhildebrandt** [comment]
Thank you @sekulicb. Will fix it tonight

**Comment by sebhildebrandt** [comment]
Fixed ... sorry for that and once again thank you.
Version 2.2.3 just published.
