### ISSUE TITLE
Feature Request: manual shutdown

### ISSUE THREAD

**Issue by jeffijoe** [sebhildebrandt/http-graceful-shutdown#7]
### Issue Type

* [ ] Bug
* [x] Feature Request
* [ ] Question

### Feature

Return a `() => Promise<void>` that can be called to trigger graceful shutdown manually.

The use case is being able to do graceful shutdown via tests:

```js
let shutdown
beforeAll(() => {
  shutdown = gracefulShutdown(...)
})

afterAll(async () => {
  await shutdown()
})
```

**Comment by sebhildebrandt** [comment]
@jeffijoe good idea. Will provide a solution for that!

**Comment by sebhildebrandt** [comment]
Hi @jeffijoe , I have a version ready, not yet published on `NPM` but here on GitHub. If you want to give it a try, I would be happy to get a feedback if this works as expected.

**Comment by jeffijoe** [comment]
I left a line comment, the promise is never resolved. 😀

**Comment by sebhildebrandt** [comment]
@jeffijoe You where absolutely right ... can you try it once more?

**Comment by jeffijoe** [comment]
You can just return the shutdown function bound with the manual string param, that way the promise also catches errors, right now errors are not passed to the manual promise.

**Comment by sebhildebrandt** [comment]
Yes, right ... then I also need to have a reject in the shutdown. corrected both ... can you once again test it?

**Comment by jeffijoe** [comment]
Took another peek, what’s this for? https://github.com/sebhildebrandt/http-graceful-shutdown/blob/2a91918e7c632b3be4e44707bc426516f732cc18/lib/index.js#L82

Shouldn’t this also trigger the entire shutdown sequence?

**Comment by sebhildebrandt** [comment]
Besides of a providing a `onShutdown` function you can also provide a (non time consuming / sync) `finally` function ... see documentation (advanced options) ... I just moved it a little to have it right before the resolve ...

**Comment by jeffijoe** [comment]
Does onShutdown run before or after the server has been drained?

**Comment by sebhildebrandt** [comment]
directly before the exit ... the order is:

- first try to clean up http/https connections
- then your onShutdown function runs (which can be a promise)... to clean up e.g. DB connections
- then the finally function runs (e.g. for a last log)
- and (in case you trigger your manual shutdown) ... `resolve` 
- then the `process.exit` happenes

**Comment by jeffijoe** [comment]
Perfect, thanks!

**Comment by sebhildebrandt** [comment]
So this works for you? then I will release a new package version

**Comment by jeffijoe** [comment]
I’lll give it a try tomorrow, but i did a quick pass over the code on my phone and it looks good so I think you can release a new version. 😀

**Comment by jeffijoe** [comment]
I think it's good to release.

**Comment by sebhildebrandt** [comment]
Version 2.3 just released
