### ISSUE TITLE
Add option to avoid process.exit

### ISSUE THREAD

**Issue by SHSP-DavidTombs** [sebhildebrandt/http-graceful-shutdown#9]
### Issue Type

* [ ] Bug
* [x] Feature Request
* [ ] Question

### Feature

Add a configuration option to avoid calling `process.exit()` once `shutdown()` finishes its work.

### Use Case

We'd rather have Node shut down when the event loop clears than have this module force an exit. We could add extra checks/waits in `onShutdown()` but just letting the event loop clear would be less code.

**Comment by acidoxee** [comment]
I'd like to second that request. I'm currently taking care of some minor corrections on our monolithic backend to make sure it integrates well with Kubernetes' probes and pod lifecycle, including gracefully shutting everything down.

Letting Node.js shut the process down naturally would probably better than forcibly killing it. Plus, there are still Kubernetes' timeout as well as your package's to make sure it still exits at some point.

**Comment by sebhildebrandt** [comment]
@acidoxee @SHSP-DavidTombs I added an option for that.  ... version 2.4.0 just released

Would you like to test it on your side?
